// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqo46yS-fqjpr6-qEC1et-qBvAm4B7Kk',
    appId: '1:111563301916:web:ce20d2387607d6d5a9abd9',
    messagingSenderId: '111563301916',
    projectId: 'brew-crew-1af1e',
    authDomain: 'brew-crew-1af1e.firebaseapp.com',
    storageBucket: 'brew-crew-1af1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZ_NjRzt-ZSdxKrBjt3M7t6ZXlooI5oc',
    appId: '1:111563301916:android:ea07573ba3951841a9abd9',
    messagingSenderId: '111563301916',
    projectId: 'brew-crew-1af1e',
    storageBucket: 'brew-crew-1af1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBloOoglu0OFZ7FfyOKZl5Kanaopym8aYY',
    appId: '1:111563301916:ios:51c6965fbf95d792a9abd9',
    messagingSenderId: '111563301916',
    projectId: 'brew-crew-1af1e',
    storageBucket: 'brew-crew-1af1e.appspot.com',
    iosClientId: '111563301916-3rdjhukt660tusbmu4jsiii8dgru45ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBloOoglu0OFZ7FfyOKZl5Kanaopym8aYY',
    appId: '1:111563301916:ios:51c6965fbf95d792a9abd9',
    messagingSenderId: '111563301916',
    projectId: 'brew-crew-1af1e',
    storageBucket: 'brew-crew-1af1e.appspot.com',
    iosClientId: '111563301916-3rdjhukt660tusbmu4jsiii8dgru45ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
